## ! Should match with the name when you turn on the synapse ! ##
#rosservice call /Axon_v2_linear/name/set "set_data: 'rHipRoll'"
#rosservice call /Axon_v2_linear_3/name/set "set_data: 'rHipYaw'"
#rosservice call /Axon_v2_linear_4/name/set "set_data: 'rHipPitch'"
#rosservice call /Axon_v2_linear_5/name/set "set_data: 'rKnee'"
#rosservice call /Axon_v2_linear_6/name/set "set_data: 'rAnkle'"
#rosservice call /Axon_v2_linear_8/name/set "set_data: 'lHipRoll'"
#rosservice call /Axon_v2_linear_9/name/set "set_data: 'lHipYaw'"
#rosservice call /Axon_v2_linear_10/name/set "set_data: 'lHipPitch'"
#rosservice call /Axon_v2_linear_11/name/set "set_data: 'lKnee'"
#rosservice call /Axon_v2_linear_12/name/set "set_data: 'lAnkle'"

rosservice call /Axon_v2_linear_debug/name/set "set_data: 'rHipRoll'"
rosservice call /Axon_v2_linear_debug_3/name/set "set_data: 'rHipYaw'"
rosservice call /Axon_v2_linear_debug_4/name/set "set_data: 'rHipPitch'"
rosservice call /Axon_v2_linear_debug_5/name/set "set_data: 'rKnee'"
rosservice call /Axon_v2_linear_debug_6/name/set "set_data: 'rAnkle'"
rosservice call /Axon_v2_linear_debug_8/name/set "set_data: 'lHipRoll'"
rosservice call /Axon_v2_linear_debug_9/name/set "set_data: 'lHipYaw'"
rosservice call /Axon_v2_linear_debug_10/name/set "set_data: 'lHipPitch'"
rosservice call /Axon_v2_linear_debug_11/name/set "set_data: 'lKnee'"
rosservice call /Axon_v2_linear_debug_12/name/set "set_data: 'lAnkle'"
