chirp:
  ######### joint chirp
  chirpType: 0 #0 : linear, 1: exponential
  startDur: 1.0
  highFreq: 10
  lowFreq: 0.001
  rate: 0.5
  amp: 0.15
  offset: 1.3
  endDur: 0.006
  ######### current chirp
  #chirpType: 0 #0 : linear, 1: exponential
  #startDur: 1.0
  #highFreq: 300
  #lowFreq: 0.001
  #rate: 0.008
  #amp: 2.0
  #offset: -3.0
  #endDur: 0.006
  ######### motor chirp
  #chirpType: 0 #0 : linear (highFreq / rate = 20), 1: exponential (highfreq*rate = 2)
  #startDur: 1.0
  #highFreq: 20
  #lowFreq: 0.001
  #rate: 1
  #amp: 8.0
  #offset: 450.0
  #endDur: 0.006
