lknee:
  joint_kp: 150.0
  joint_kd: 5.0
  torque_kp: 2.0
  torque_kd: 0.01
  #torque_kp: 0.0
  #torque_kd: 0.0
  current_limit: 3.0
  enable_dob: 0
  enable_spring: 0
  jPosFeedbackSrc: 2 #2: motor position feedback, 1: joint position feedback

lankle:
  joint_kp: 18.0
  joint_kd: 1.5
  torque_kp: 0.0
  torque_kd: 0.0
  current_limit: 3.0
  enable_dob: 0
  enable_spring: 0
  jPosFeedbackSrc: 2 #2: motor position feedback, 1: joint position feedback

rKnee:
  #joint_kp: 100.0
  #joint_kd: 8.0
  joint_kp: 0.0
  joint_kd: 0.0
  #torque_kp: 0.01
  #torque_kd: 0.001
  #joint_kp: 100.0
  #joint_kd: 10.0
  #joint_kp: 30.0
  #joint_kd: 4.0
  torque_kp: 0.0
  torque_kd: 0.0
  current_limit: 6.0
  enable_dob: 0
  enable_spring: 0
  jPosFeedbackSrc: 2 #2: motor position feedback, 1: joint position feedback

rAnkle:
  joint_kp: 18.0
  joint_kd: 1.5
  #joint_kp: 0.0
  #joint_kd: 0.0
  torque_kp: 0.0
  torque_kd: 0.0
  current_limit: 6.0
  enable_dob: 0
  enable_spring: 0
  jPosFeedbackSrc: 2 #2: motor position feedback, 1: joint position feedback
