lknee:
  joint_kp: 150.0
  joint_kd: 5.0
  torque_kp: 2.0
  torque_kd: 0.01
  #torque_kp: 0.0
  #torque_kd: 0.0
  current_limit: 3.0
  enable_dob: 0

lankle:
  joint_kp: 18.0
  joint_kd: 1.5
  torque_kp: 0.0
  torque_kd: 0.0
  current_limit: 3.0
  enable_dob: 0

rKnee:
  joint_kp: 150.0
  joint_kd: 5.0
  #torque_kp: 2.0
  #torque_kd: 0.01
  torque_kp: 0.0
  torque_kd: 0.0
  current_limit: 6.0
  enable_dob: 0

rAnkle:
  #joint_kp: 18.0
  #joint_kd: 1.5
  joint_kp: 0.0
  joint_kd: 0.0
  torque_kp: 0.0
  torque_kd: 0.0
  current_limit: 0.1
  enable_dob: 0
