chirp:
  ######### joint chirp
  #chirpType: 0 #0 : linear, 1: exponential
  #startDur: 1.0
  #highFreq: 20
  #lowFreq: 0.001
  #rate: 0.1
  #amp: 0.05
  #offset: 0.85
  #endDur: 0.006
  ######### current chirp
  #chirpType: 0 #0 : linear, 1: exponential
  #startDur: 1.0
  #highFreq: 300
  #lowFreq: 0.001
  #rate: 0.008
  #amp: 2.0
  #offset: -3.0
  #endDur: 0.006
  ######### motor chirp
  chirpType: 0 #0 : linear (highFreq / rate = 20), 1: exponential (highfreq*rate = 2)
  startDur: 1.0
  highFreq: 25
  lowFreq: 0.001
  rate: 1
  #rate: 0.1
  amp: 3.0
  offset: 353.0
  endDur: 0.006
